/*@ begin PerfTuning (
 def build {
   arg build_command = 'gcc -O0 -mcmodel=large';
 }
 def performance_params {
   param UF[] = range(1,33);
 }
 def performance_counter {
  arg method = 'basic timer';
  arg repetitions = 10;
 }
 def input_params {
   param N[] = [100000000];
 }
 def input_vars {
   decl static double y[N] = random;
   decl double a1 = random;
   decl double a2 = random;
   decl double a3 = random;
   decl static double x1[N] = random;
   decl static double x2[N] = random;
   decl static double x3[N] = random;
 }

 def search {
  arg algorithm = 'Randomsearch';
  arg time_limit = 10;
  arg total_runs = 10;
 }
) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.384175, 0.380792, 0.382608, 0.383474, 0.382642, 0.384184, 0.388893, 0.383627, 0.385163, 0.44838] 
Tuned for specific problem sizes: 
  N = 100000000 
Best performance parameters: 
  UF = 5 
--**/

int i;
/*@ begin Loop (
    transform Unroll(ufactor=UF)
    for (i=0; i<=N-1; i++)
      y[i] = y[i] + a1*x1[i] + a2*x2[i] + a3*x3[i];
) @*/
for (int loop_loop_34=0; loop_loop_34 < 1; loop_loop_34++)  {
    int i;
    for (i = 0; i <= N - 5; i = i + 5) {
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
      y[(i + 1)] = y[(i + 1)] + a1 * x1[(i + 1)] + a2 * x2[(i + 1)] + a3 * x3[(i + 1)];
      y[(i + 2)] = y[(i + 2)] + a1 * x1[(i + 2)] + a2 * x2[(i + 2)] + a3 * x3[(i + 2)];
      y[(i + 3)] = y[(i + 3)] + a1 * x1[(i + 3)] + a2 * x2[(i + 3)] + a3 * x3[(i + 3)];
      y[(i + 4)] = y[(i + 4)] + a1 * x1[(i + 4)] + a2 * x2[(i + 4)] + a3 * x3[(i + 4)];
    }
    for (i = N - ((N - (0)) % 5); i <= N - 1; i = i + 1) 
      y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i];
  }
/*@ end @*/
/*@ end @*/
